version: '3.8'

services:
  pocket-users:
    build:
      context: .
      target: development
    container_name: pocket-users
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - pocket-network
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
      - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./mongo/replica.key:/data/replica.key.devel
    entrypoint:
      - bash
      - -c
      - |
        cp /data/replica.key.devel /data/replicacopy.key
        chmod 400 /data/replicacopy.key
        chown 999:999 /data/replicacopy.key
        exec docker-entrypoint.sh $$@
    command: 'mongod --replSet replicaSet01 --keyFile /data/replicacopy.key'
    ports:
      - 27017:27017
    networks:
      - pocket-network

networks:
  pocket-network:
    external: true
